//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Tests.TestsBase;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of Pressure.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class PressureTestsBase : QuantityTestsBase
    {
        protected abstract double AtmospheresInOnePascal { get; }
        protected abstract double BarsInOnePascal { get; }
        protected abstract double CentibarsInOnePascal { get; }
        protected abstract double CentimetersOfWaterConventionalInOnePascal { get; }
        protected abstract double DecapascalsInOnePascal { get; }
        protected abstract double DecibarsInOnePascal { get; }
        protected abstract double DynesPerSquareCentimeterInOnePascal { get; }
        protected abstract double FeetOfElevationInOnePascal { get; }
        protected abstract double FeetOfHeadInOnePascal { get; }
        protected abstract double FeetOfWaterConventionalInOnePascal { get; }
        protected abstract double GigapascalsInOnePascal { get; }
        protected abstract double HectopascalsInOnePascal { get; }
        protected abstract double InchesOfMercuryInOnePascal { get; }
        protected abstract double InchesOfWaterColumnInOnePascal { get; }
        protected abstract double InchesOfWaterConventionalInOnePascal { get; }
        protected abstract double KilobarsInOnePascal { get; }
        protected abstract double KilogramsForcePerSquareCentimeterInOnePascal { get; }
        protected abstract double KilogramsForcePerSquareMeterInOnePascal { get; }
        protected abstract double KilogramsForcePerSquareMillimeterInOnePascal { get; }
        protected abstract double KilonewtonsPerSquareCentimeterInOnePascal { get; }
        protected abstract double KilonewtonsPerSquareMeterInOnePascal { get; }
        protected abstract double KilonewtonsPerSquareMillimeterInOnePascal { get; }
        protected abstract double KilopascalsInOnePascal { get; }
        protected abstract double KilopoundsForcePerSquareFootInOnePascal { get; }
        protected abstract double KilopoundsForcePerSquareInchInOnePascal { get; }
        protected abstract double MegabarsInOnePascal { get; }
        protected abstract double MeganewtonsPerSquareMeterInOnePascal { get; }
        protected abstract double MegapascalsInOnePascal { get; }
        protected abstract double MetersOfElevationInOnePascal { get; }
        protected abstract double MetersOfHeadInOnePascal { get; }
        protected abstract double MetersOfWaterConventionalInOnePascal { get; }
        protected abstract double MicrobarsInOnePascal { get; }
        protected abstract double MicropascalsInOnePascal { get; }
        protected abstract double MillibarsInOnePascal { get; }
        protected abstract double MillimetersOfMercuryInOnePascal { get; }
        protected abstract double MillimetersOfWaterConventionalInOnePascal { get; }
        protected abstract double MillipascalsInOnePascal { get; }
        protected abstract double NewtonsPerSquareCentimeterInOnePascal { get; }
        protected abstract double NewtonsPerSquareMeterInOnePascal { get; }
        protected abstract double NewtonsPerSquareMillimeterInOnePascal { get; }
        protected abstract double PascalsInOnePascal { get; }
        protected abstract double PoundsForcePerSquareFootInOnePascal { get; }
        protected abstract double PoundsForcePerSquareInchInOnePascal { get; }
        protected abstract double PoundsPerInchSecondSquaredInOnePascal { get; }
        protected abstract double TechnicalAtmospheresInOnePascal { get; }
        protected abstract double TonnesForcePerSquareCentimeterInOnePascal { get; }
        protected abstract double TonnesForcePerSquareMeterInOnePascal { get; }
        protected abstract double TonnesForcePerSquareMillimeterInOnePascal { get; }
        protected abstract double TorrsInOnePascal { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double AtmospheresTolerance { get { return 1e-5; } }
        protected virtual double BarsTolerance { get { return 1e-5; } }
        protected virtual double CentibarsTolerance { get { return 1e-5; } }
        protected virtual double CentimetersOfWaterConventionalTolerance { get { return 1e-5; } }
        protected virtual double DecapascalsTolerance { get { return 1e-5; } }
        protected virtual double DecibarsTolerance { get { return 1e-5; } }
        protected virtual double DynesPerSquareCentimeterTolerance { get { return 1e-5; } }
        protected virtual double FeetOfElevationTolerance { get { return 1e-5; } }
        protected virtual double FeetOfHeadTolerance { get { return 1e-5; } }
        protected virtual double FeetOfWaterConventionalTolerance { get { return 1e-5; } }
        protected virtual double GigapascalsTolerance { get { return 1e-5; } }
        protected virtual double HectopascalsTolerance { get { return 1e-5; } }
        protected virtual double InchesOfMercuryTolerance { get { return 1e-5; } }
        protected virtual double InchesOfWaterColumnTolerance { get { return 1e-5; } }
        protected virtual double InchesOfWaterConventionalTolerance { get { return 1e-5; } }
        protected virtual double KilobarsTolerance { get { return 1e-5; } }
        protected virtual double KilogramsForcePerSquareCentimeterTolerance { get { return 1e-5; } }
        protected virtual double KilogramsForcePerSquareMeterTolerance { get { return 1e-5; } }
        protected virtual double KilogramsForcePerSquareMillimeterTolerance { get { return 1e-5; } }
        protected virtual double KilonewtonsPerSquareCentimeterTolerance { get { return 1e-5; } }
        protected virtual double KilonewtonsPerSquareMeterTolerance { get { return 1e-5; } }
        protected virtual double KilonewtonsPerSquareMillimeterTolerance { get { return 1e-5; } }
        protected virtual double KilopascalsTolerance { get { return 1e-5; } }
        protected virtual double KilopoundsForcePerSquareFootTolerance { get { return 1e-5; } }
        protected virtual double KilopoundsForcePerSquareInchTolerance { get { return 1e-5; } }
        protected virtual double MegabarsTolerance { get { return 1e-5; } }
        protected virtual double MeganewtonsPerSquareMeterTolerance { get { return 1e-5; } }
        protected virtual double MegapascalsTolerance { get { return 1e-5; } }
        protected virtual double MetersOfElevationTolerance { get { return 1e-5; } }
        protected virtual double MetersOfHeadTolerance { get { return 1e-5; } }
        protected virtual double MetersOfWaterConventionalTolerance { get { return 1e-5; } }
        protected virtual double MicrobarsTolerance { get { return 1e-5; } }
        protected virtual double MicropascalsTolerance { get { return 1e-5; } }
        protected virtual double MillibarsTolerance { get { return 1e-5; } }
        protected virtual double MillimetersOfMercuryTolerance { get { return 1e-5; } }
        protected virtual double MillimetersOfWaterConventionalTolerance { get { return 1e-5; } }
        protected virtual double MillipascalsTolerance { get { return 1e-5; } }
        protected virtual double NewtonsPerSquareCentimeterTolerance { get { return 1e-5; } }
        protected virtual double NewtonsPerSquareMeterTolerance { get { return 1e-5; } }
        protected virtual double NewtonsPerSquareMillimeterTolerance { get { return 1e-5; } }
        protected virtual double PascalsTolerance { get { return 1e-5; } }
        protected virtual double PoundsForcePerSquareFootTolerance { get { return 1e-5; } }
        protected virtual double PoundsForcePerSquareInchTolerance { get { return 1e-5; } }
        protected virtual double PoundsPerInchSecondSquaredTolerance { get { return 1e-5; } }
        protected virtual double TechnicalAtmospheresTolerance { get { return 1e-5; } }
        protected virtual double TonnesForcePerSquareCentimeterTolerance { get { return 1e-5; } }
        protected virtual double TonnesForcePerSquareMeterTolerance { get { return 1e-5; } }
        protected virtual double TonnesForcePerSquareMillimeterTolerance { get { return 1e-5; } }
        protected virtual double TorrsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void Ctor_WithUndefinedUnit_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Pressure((double)0.0, PressureUnit.Undefined));
        }

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new Pressure();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(PressureUnit.Pascal, quantity.Unit);
        }


        [Fact]
        public void Ctor_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Pressure(double.PositiveInfinity, PressureUnit.Pascal));
            Assert.Throws<ArgumentException>(() => new Pressure(double.NegativeInfinity, PressureUnit.Pascal));
        }

        [Fact]
        public void Ctor_WithNaNValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => new Pressure(double.NaN, PressureUnit.Pascal));
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new Pressure(value: 1, unitSystem: null));
        }

        [Fact]
        public void Ctor_SIUnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            Func<object> TestCode = () => new Pressure(value: 1, unitSystem: UnitSystem.SI);
            if (SupportsSIUnitSystem)
            {
                var quantity = (Pressure) TestCode();
                Assert.Equal(1, quantity.Value);
            }
            else
            {
                Assert.Throws<ArgumentException>(TestCode);
            }
        }

        [Fact]
        public void Pressure_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new Pressure(1, PressureUnit.Pascal);

            QuantityInfo<PressureUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(Pressure.Zero, quantityInfo.Zero);
            Assert.Equal("Pressure", quantityInfo.Name);
            Assert.Equal(QuantityType.Pressure, quantityInfo.QuantityType);

            var units = EnumUtils.GetEnumValues<PressureUnit>().Except(new[] {PressureUnit.Undefined}).ToArray();
            var unitNames = units.Select(x => x.ToString());

            // Obsolete members
            Assert.Equal(units, quantityInfo.Units);
            Assert.Equal(unitNames, quantityInfo.UnitNames);
        }

        [Fact]
        public void PascalToPressureUnits()
        {
            Pressure pascal = Pressure.FromPascals(1);
            AssertEx.EqualTolerance(AtmospheresInOnePascal, pascal.Atmospheres, AtmospheresTolerance);
            AssertEx.EqualTolerance(BarsInOnePascal, pascal.Bars, BarsTolerance);
            AssertEx.EqualTolerance(CentibarsInOnePascal, pascal.Centibars, CentibarsTolerance);
            AssertEx.EqualTolerance(CentimetersOfWaterConventionalInOnePascal, pascal.CentimetersOfWaterConventional, CentimetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(DecapascalsInOnePascal, pascal.Decapascals, DecapascalsTolerance);
            AssertEx.EqualTolerance(DecibarsInOnePascal, pascal.Decibars, DecibarsTolerance);
            AssertEx.EqualTolerance(DynesPerSquareCentimeterInOnePascal, pascal.DynesPerSquareCentimeter, DynesPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(FeetOfElevationInOnePascal, pascal.FeetOfElevation, FeetOfElevationTolerance);
            AssertEx.EqualTolerance(FeetOfHeadInOnePascal, pascal.FeetOfHead, FeetOfHeadTolerance);
            AssertEx.EqualTolerance(FeetOfWaterConventionalInOnePascal, pascal.FeetOfWaterConventional, FeetOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(GigapascalsInOnePascal, pascal.Gigapascals, GigapascalsTolerance);
            AssertEx.EqualTolerance(HectopascalsInOnePascal, pascal.Hectopascals, HectopascalsTolerance);
            AssertEx.EqualTolerance(InchesOfMercuryInOnePascal, pascal.InchesOfMercury, InchesOfMercuryTolerance);
            AssertEx.EqualTolerance(InchesOfWaterColumnInOnePascal, pascal.InchesOfWaterColumn, InchesOfWaterColumnTolerance);
            AssertEx.EqualTolerance(InchesOfWaterConventionalInOnePascal, pascal.InchesOfWaterConventional, InchesOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(KilobarsInOnePascal, pascal.Kilobars, KilobarsTolerance);
            AssertEx.EqualTolerance(KilogramsForcePerSquareCentimeterInOnePascal, pascal.KilogramsForcePerSquareCentimeter, KilogramsForcePerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(KilogramsForcePerSquareMeterInOnePascal, pascal.KilogramsForcePerSquareMeter, KilogramsForcePerSquareMeterTolerance);
            AssertEx.EqualTolerance(KilogramsForcePerSquareMillimeterInOnePascal, pascal.KilogramsForcePerSquareMillimeter, KilogramsForcePerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(KilonewtonsPerSquareCentimeterInOnePascal, pascal.KilonewtonsPerSquareCentimeter, KilonewtonsPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(KilonewtonsPerSquareMeterInOnePascal, pascal.KilonewtonsPerSquareMeter, KilonewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(KilonewtonsPerSquareMillimeterInOnePascal, pascal.KilonewtonsPerSquareMillimeter, KilonewtonsPerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(KilopascalsInOnePascal, pascal.Kilopascals, KilopascalsTolerance);
            AssertEx.EqualTolerance(KilopoundsForcePerSquareFootInOnePascal, pascal.KilopoundsForcePerSquareFoot, KilopoundsForcePerSquareFootTolerance);
            AssertEx.EqualTolerance(KilopoundsForcePerSquareInchInOnePascal, pascal.KilopoundsForcePerSquareInch, KilopoundsForcePerSquareInchTolerance);
            AssertEx.EqualTolerance(MegabarsInOnePascal, pascal.Megabars, MegabarsTolerance);
            AssertEx.EqualTolerance(MeganewtonsPerSquareMeterInOnePascal, pascal.MeganewtonsPerSquareMeter, MeganewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(MegapascalsInOnePascal, pascal.Megapascals, MegapascalsTolerance);
            AssertEx.EqualTolerance(MetersOfElevationInOnePascal, pascal.MetersOfElevation, MetersOfElevationTolerance);
            AssertEx.EqualTolerance(MetersOfHeadInOnePascal, pascal.MetersOfHead, MetersOfHeadTolerance);
            AssertEx.EqualTolerance(MetersOfWaterConventionalInOnePascal, pascal.MetersOfWaterConventional, MetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(MicrobarsInOnePascal, pascal.Microbars, MicrobarsTolerance);
            AssertEx.EqualTolerance(MicropascalsInOnePascal, pascal.Micropascals, MicropascalsTolerance);
            AssertEx.EqualTolerance(MillibarsInOnePascal, pascal.Millibars, MillibarsTolerance);
            AssertEx.EqualTolerance(MillimetersOfMercuryInOnePascal, pascal.MillimetersOfMercury, MillimetersOfMercuryTolerance);
            AssertEx.EqualTolerance(MillimetersOfWaterConventionalInOnePascal, pascal.MillimetersOfWaterConventional, MillimetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(MillipascalsInOnePascal, pascal.Millipascals, MillipascalsTolerance);
            AssertEx.EqualTolerance(NewtonsPerSquareCentimeterInOnePascal, pascal.NewtonsPerSquareCentimeter, NewtonsPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(NewtonsPerSquareMeterInOnePascal, pascal.NewtonsPerSquareMeter, NewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(NewtonsPerSquareMillimeterInOnePascal, pascal.NewtonsPerSquareMillimeter, NewtonsPerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(PascalsInOnePascal, pascal.Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(PoundsForcePerSquareFootInOnePascal, pascal.PoundsForcePerSquareFoot, PoundsForcePerSquareFootTolerance);
            AssertEx.EqualTolerance(PoundsForcePerSquareInchInOnePascal, pascal.PoundsForcePerSquareInch, PoundsForcePerSquareInchTolerance);
            AssertEx.EqualTolerance(PoundsPerInchSecondSquaredInOnePascal, pascal.PoundsPerInchSecondSquared, PoundsPerInchSecondSquaredTolerance);
            AssertEx.EqualTolerance(TechnicalAtmospheresInOnePascal, pascal.TechnicalAtmospheres, TechnicalAtmospheresTolerance);
            AssertEx.EqualTolerance(TonnesForcePerSquareCentimeterInOnePascal, pascal.TonnesForcePerSquareCentimeter, TonnesForcePerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(TonnesForcePerSquareMeterInOnePascal, pascal.TonnesForcePerSquareMeter, TonnesForcePerSquareMeterTolerance);
            AssertEx.EqualTolerance(TonnesForcePerSquareMillimeterInOnePascal, pascal.TonnesForcePerSquareMillimeter, TonnesForcePerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(TorrsInOnePascal, pascal.Torrs, TorrsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = Pressure.From(1, PressureUnit.Atmosphere);
            AssertEx.EqualTolerance(1, quantity00.Atmospheres, AtmospheresTolerance);
            Assert.Equal(PressureUnit.Atmosphere, quantity00.Unit);

            var quantity01 = Pressure.From(1, PressureUnit.Bar);
            AssertEx.EqualTolerance(1, quantity01.Bars, BarsTolerance);
            Assert.Equal(PressureUnit.Bar, quantity01.Unit);

            var quantity02 = Pressure.From(1, PressureUnit.Centibar);
            AssertEx.EqualTolerance(1, quantity02.Centibars, CentibarsTolerance);
            Assert.Equal(PressureUnit.Centibar, quantity02.Unit);

            var quantity03 = Pressure.From(1, PressureUnit.CentimeterOfWaterConventional);
            AssertEx.EqualTolerance(1, quantity03.CentimetersOfWaterConventional, CentimetersOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.CentimeterOfWaterConventional, quantity03.Unit);

            var quantity04 = Pressure.From(1, PressureUnit.Decapascal);
            AssertEx.EqualTolerance(1, quantity04.Decapascals, DecapascalsTolerance);
            Assert.Equal(PressureUnit.Decapascal, quantity04.Unit);

            var quantity05 = Pressure.From(1, PressureUnit.Decibar);
            AssertEx.EqualTolerance(1, quantity05.Decibars, DecibarsTolerance);
            Assert.Equal(PressureUnit.Decibar, quantity05.Unit);

            var quantity06 = Pressure.From(1, PressureUnit.DynePerSquareCentimeter);
            AssertEx.EqualTolerance(1, quantity06.DynesPerSquareCentimeter, DynesPerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.DynePerSquareCentimeter, quantity06.Unit);

            var quantity07 = Pressure.From(1, PressureUnit.FootOfElevation);
            AssertEx.EqualTolerance(1, quantity07.FeetOfElevation, FeetOfElevationTolerance);
            Assert.Equal(PressureUnit.FootOfElevation, quantity07.Unit);

            var quantity08 = Pressure.From(1, PressureUnit.FootOfHead);
            AssertEx.EqualTolerance(1, quantity08.FeetOfHead, FeetOfHeadTolerance);
            Assert.Equal(PressureUnit.FootOfHead, quantity08.Unit);

            var quantity09 = Pressure.From(1, PressureUnit.FootOfWaterConventional);
            AssertEx.EqualTolerance(1, quantity09.FeetOfWaterConventional, FeetOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.FootOfWaterConventional, quantity09.Unit);

            var quantity10 = Pressure.From(1, PressureUnit.Gigapascal);
            AssertEx.EqualTolerance(1, quantity10.Gigapascals, GigapascalsTolerance);
            Assert.Equal(PressureUnit.Gigapascal, quantity10.Unit);

            var quantity11 = Pressure.From(1, PressureUnit.Hectopascal);
            AssertEx.EqualTolerance(1, quantity11.Hectopascals, HectopascalsTolerance);
            Assert.Equal(PressureUnit.Hectopascal, quantity11.Unit);

            var quantity12 = Pressure.From(1, PressureUnit.InchOfMercury);
            AssertEx.EqualTolerance(1, quantity12.InchesOfMercury, InchesOfMercuryTolerance);
            Assert.Equal(PressureUnit.InchOfMercury, quantity12.Unit);

            var quantity13 = Pressure.From(1, PressureUnit.InchOfWaterColumn);
            AssertEx.EqualTolerance(1, quantity13.InchesOfWaterColumn, InchesOfWaterColumnTolerance);
            Assert.Equal(PressureUnit.InchOfWaterColumn, quantity13.Unit);

            var quantity14 = Pressure.From(1, PressureUnit.InchOfWaterConventional);
            AssertEx.EqualTolerance(1, quantity14.InchesOfWaterConventional, InchesOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.InchOfWaterConventional, quantity14.Unit);

            var quantity15 = Pressure.From(1, PressureUnit.Kilobar);
            AssertEx.EqualTolerance(1, quantity15.Kilobars, KilobarsTolerance);
            Assert.Equal(PressureUnit.Kilobar, quantity15.Unit);

            var quantity16 = Pressure.From(1, PressureUnit.KilogramForcePerSquareCentimeter);
            AssertEx.EqualTolerance(1, quantity16.KilogramsForcePerSquareCentimeter, KilogramsForcePerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.KilogramForcePerSquareCentimeter, quantity16.Unit);

            var quantity17 = Pressure.From(1, PressureUnit.KilogramForcePerSquareMeter);
            AssertEx.EqualTolerance(1, quantity17.KilogramsForcePerSquareMeter, KilogramsForcePerSquareMeterTolerance);
            Assert.Equal(PressureUnit.KilogramForcePerSquareMeter, quantity17.Unit);

            var quantity18 = Pressure.From(1, PressureUnit.KilogramForcePerSquareMillimeter);
            AssertEx.EqualTolerance(1, quantity18.KilogramsForcePerSquareMillimeter, KilogramsForcePerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.KilogramForcePerSquareMillimeter, quantity18.Unit);

            var quantity19 = Pressure.From(1, PressureUnit.KilonewtonPerSquareCentimeter);
            AssertEx.EqualTolerance(1, quantity19.KilonewtonsPerSquareCentimeter, KilonewtonsPerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.KilonewtonPerSquareCentimeter, quantity19.Unit);

            var quantity20 = Pressure.From(1, PressureUnit.KilonewtonPerSquareMeter);
            AssertEx.EqualTolerance(1, quantity20.KilonewtonsPerSquareMeter, KilonewtonsPerSquareMeterTolerance);
            Assert.Equal(PressureUnit.KilonewtonPerSquareMeter, quantity20.Unit);

            var quantity21 = Pressure.From(1, PressureUnit.KilonewtonPerSquareMillimeter);
            AssertEx.EqualTolerance(1, quantity21.KilonewtonsPerSquareMillimeter, KilonewtonsPerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.KilonewtonPerSquareMillimeter, quantity21.Unit);

            var quantity22 = Pressure.From(1, PressureUnit.Kilopascal);
            AssertEx.EqualTolerance(1, quantity22.Kilopascals, KilopascalsTolerance);
            Assert.Equal(PressureUnit.Kilopascal, quantity22.Unit);

            var quantity23 = Pressure.From(1, PressureUnit.KilopoundForcePerSquareFoot);
            AssertEx.EqualTolerance(1, quantity23.KilopoundsForcePerSquareFoot, KilopoundsForcePerSquareFootTolerance);
            Assert.Equal(PressureUnit.KilopoundForcePerSquareFoot, quantity23.Unit);

            var quantity24 = Pressure.From(1, PressureUnit.KilopoundForcePerSquareInch);
            AssertEx.EqualTolerance(1, quantity24.KilopoundsForcePerSquareInch, KilopoundsForcePerSquareInchTolerance);
            Assert.Equal(PressureUnit.KilopoundForcePerSquareInch, quantity24.Unit);

            var quantity25 = Pressure.From(1, PressureUnit.Megabar);
            AssertEx.EqualTolerance(1, quantity25.Megabars, MegabarsTolerance);
            Assert.Equal(PressureUnit.Megabar, quantity25.Unit);

            var quantity26 = Pressure.From(1, PressureUnit.MeganewtonPerSquareMeter);
            AssertEx.EqualTolerance(1, quantity26.MeganewtonsPerSquareMeter, MeganewtonsPerSquareMeterTolerance);
            Assert.Equal(PressureUnit.MeganewtonPerSquareMeter, quantity26.Unit);

            var quantity27 = Pressure.From(1, PressureUnit.Megapascal);
            AssertEx.EqualTolerance(1, quantity27.Megapascals, MegapascalsTolerance);
            Assert.Equal(PressureUnit.Megapascal, quantity27.Unit);

            var quantity28 = Pressure.From(1, PressureUnit.MeterOfElevation);
            AssertEx.EqualTolerance(1, quantity28.MetersOfElevation, MetersOfElevationTolerance);
            Assert.Equal(PressureUnit.MeterOfElevation, quantity28.Unit);

            var quantity29 = Pressure.From(1, PressureUnit.MeterOfHead);
            AssertEx.EqualTolerance(1, quantity29.MetersOfHead, MetersOfHeadTolerance);
            Assert.Equal(PressureUnit.MeterOfHead, quantity29.Unit);

            var quantity30 = Pressure.From(1, PressureUnit.MeterOfWaterConventional);
            AssertEx.EqualTolerance(1, quantity30.MetersOfWaterConventional, MetersOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.MeterOfWaterConventional, quantity30.Unit);

            var quantity31 = Pressure.From(1, PressureUnit.Microbar);
            AssertEx.EqualTolerance(1, quantity31.Microbars, MicrobarsTolerance);
            Assert.Equal(PressureUnit.Microbar, quantity31.Unit);

            var quantity32 = Pressure.From(1, PressureUnit.Micropascal);
            AssertEx.EqualTolerance(1, quantity32.Micropascals, MicropascalsTolerance);
            Assert.Equal(PressureUnit.Micropascal, quantity32.Unit);

            var quantity33 = Pressure.From(1, PressureUnit.Millibar);
            AssertEx.EqualTolerance(1, quantity33.Millibars, MillibarsTolerance);
            Assert.Equal(PressureUnit.Millibar, quantity33.Unit);

            var quantity34 = Pressure.From(1, PressureUnit.MillimeterOfMercury);
            AssertEx.EqualTolerance(1, quantity34.MillimetersOfMercury, MillimetersOfMercuryTolerance);
            Assert.Equal(PressureUnit.MillimeterOfMercury, quantity34.Unit);

            var quantity35 = Pressure.From(1, PressureUnit.MillimeterOfWaterConventional);
            AssertEx.EqualTolerance(1, quantity35.MillimetersOfWaterConventional, MillimetersOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.MillimeterOfWaterConventional, quantity35.Unit);

            var quantity36 = Pressure.From(1, PressureUnit.Millipascal);
            AssertEx.EqualTolerance(1, quantity36.Millipascals, MillipascalsTolerance);
            Assert.Equal(PressureUnit.Millipascal, quantity36.Unit);

            var quantity37 = Pressure.From(1, PressureUnit.NewtonPerSquareCentimeter);
            AssertEx.EqualTolerance(1, quantity37.NewtonsPerSquareCentimeter, NewtonsPerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.NewtonPerSquareCentimeter, quantity37.Unit);

            var quantity38 = Pressure.From(1, PressureUnit.NewtonPerSquareMeter);
            AssertEx.EqualTolerance(1, quantity38.NewtonsPerSquareMeter, NewtonsPerSquareMeterTolerance);
            Assert.Equal(PressureUnit.NewtonPerSquareMeter, quantity38.Unit);

            var quantity39 = Pressure.From(1, PressureUnit.NewtonPerSquareMillimeter);
            AssertEx.EqualTolerance(1, quantity39.NewtonsPerSquareMillimeter, NewtonsPerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.NewtonPerSquareMillimeter, quantity39.Unit);

            var quantity40 = Pressure.From(1, PressureUnit.Pascal);
            AssertEx.EqualTolerance(1, quantity40.Pascals, PascalsTolerance);
            Assert.Equal(PressureUnit.Pascal, quantity40.Unit);

            var quantity41 = Pressure.From(1, PressureUnit.PoundForcePerSquareFoot);
            AssertEx.EqualTolerance(1, quantity41.PoundsForcePerSquareFoot, PoundsForcePerSquareFootTolerance);
            Assert.Equal(PressureUnit.PoundForcePerSquareFoot, quantity41.Unit);

            var quantity42 = Pressure.From(1, PressureUnit.PoundForcePerSquareInch);
            AssertEx.EqualTolerance(1, quantity42.PoundsForcePerSquareInch, PoundsForcePerSquareInchTolerance);
            Assert.Equal(PressureUnit.PoundForcePerSquareInch, quantity42.Unit);

            var quantity43 = Pressure.From(1, PressureUnit.PoundPerInchSecondSquared);
            AssertEx.EqualTolerance(1, quantity43.PoundsPerInchSecondSquared, PoundsPerInchSecondSquaredTolerance);
            Assert.Equal(PressureUnit.PoundPerInchSecondSquared, quantity43.Unit);

            var quantity44 = Pressure.From(1, PressureUnit.TechnicalAtmosphere);
            AssertEx.EqualTolerance(1, quantity44.TechnicalAtmospheres, TechnicalAtmospheresTolerance);
            Assert.Equal(PressureUnit.TechnicalAtmosphere, quantity44.Unit);

            var quantity45 = Pressure.From(1, PressureUnit.TonneForcePerSquareCentimeter);
            AssertEx.EqualTolerance(1, quantity45.TonnesForcePerSquareCentimeter, TonnesForcePerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.TonneForcePerSquareCentimeter, quantity45.Unit);

            var quantity46 = Pressure.From(1, PressureUnit.TonneForcePerSquareMeter);
            AssertEx.EqualTolerance(1, quantity46.TonnesForcePerSquareMeter, TonnesForcePerSquareMeterTolerance);
            Assert.Equal(PressureUnit.TonneForcePerSquareMeter, quantity46.Unit);

            var quantity47 = Pressure.From(1, PressureUnit.TonneForcePerSquareMillimeter);
            AssertEx.EqualTolerance(1, quantity47.TonnesForcePerSquareMillimeter, TonnesForcePerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.TonneForcePerSquareMillimeter, quantity47.Unit);

            var quantity48 = Pressure.From(1, PressureUnit.Torr);
            AssertEx.EqualTolerance(1, quantity48.Torrs, TorrsTolerance);
            Assert.Equal(PressureUnit.Torr, quantity48.Unit);

        }

        [Fact]
        public void FromPascals_WithInfinityValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => Pressure.FromPascals(double.PositiveInfinity));
            Assert.Throws<ArgumentException>(() => Pressure.FromPascals(double.NegativeInfinity));
        }

        [Fact]
        public void FromPascals_WithNanValue_ThrowsArgumentException()
        {
            Assert.Throws<ArgumentException>(() => Pressure.FromPascals(double.NaN));
        }

        [Fact]
        public void As()
        {
            var pascal = Pressure.FromPascals(1);
            AssertEx.EqualTolerance(AtmospheresInOnePascal, pascal.As(PressureUnit.Atmosphere), AtmospheresTolerance);
            AssertEx.EqualTolerance(BarsInOnePascal, pascal.As(PressureUnit.Bar), BarsTolerance);
            AssertEx.EqualTolerance(CentibarsInOnePascal, pascal.As(PressureUnit.Centibar), CentibarsTolerance);
            AssertEx.EqualTolerance(CentimetersOfWaterConventionalInOnePascal, pascal.As(PressureUnit.CentimeterOfWaterConventional), CentimetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(DecapascalsInOnePascal, pascal.As(PressureUnit.Decapascal), DecapascalsTolerance);
            AssertEx.EqualTolerance(DecibarsInOnePascal, pascal.As(PressureUnit.Decibar), DecibarsTolerance);
            AssertEx.EqualTolerance(DynesPerSquareCentimeterInOnePascal, pascal.As(PressureUnit.DynePerSquareCentimeter), DynesPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(FeetOfElevationInOnePascal, pascal.As(PressureUnit.FootOfElevation), FeetOfElevationTolerance);
            AssertEx.EqualTolerance(FeetOfHeadInOnePascal, pascal.As(PressureUnit.FootOfHead), FeetOfHeadTolerance);
            AssertEx.EqualTolerance(FeetOfWaterConventionalInOnePascal, pascal.As(PressureUnit.FootOfWaterConventional), FeetOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(GigapascalsInOnePascal, pascal.As(PressureUnit.Gigapascal), GigapascalsTolerance);
            AssertEx.EqualTolerance(HectopascalsInOnePascal, pascal.As(PressureUnit.Hectopascal), HectopascalsTolerance);
            AssertEx.EqualTolerance(InchesOfMercuryInOnePascal, pascal.As(PressureUnit.InchOfMercury), InchesOfMercuryTolerance);
            AssertEx.EqualTolerance(InchesOfWaterColumnInOnePascal, pascal.As(PressureUnit.InchOfWaterColumn), InchesOfWaterColumnTolerance);
            AssertEx.EqualTolerance(InchesOfWaterConventionalInOnePascal, pascal.As(PressureUnit.InchOfWaterConventional), InchesOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(KilobarsInOnePascal, pascal.As(PressureUnit.Kilobar), KilobarsTolerance);
            AssertEx.EqualTolerance(KilogramsForcePerSquareCentimeterInOnePascal, pascal.As(PressureUnit.KilogramForcePerSquareCentimeter), KilogramsForcePerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(KilogramsForcePerSquareMeterInOnePascal, pascal.As(PressureUnit.KilogramForcePerSquareMeter), KilogramsForcePerSquareMeterTolerance);
            AssertEx.EqualTolerance(KilogramsForcePerSquareMillimeterInOnePascal, pascal.As(PressureUnit.KilogramForcePerSquareMillimeter), KilogramsForcePerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(KilonewtonsPerSquareCentimeterInOnePascal, pascal.As(PressureUnit.KilonewtonPerSquareCentimeter), KilonewtonsPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(KilonewtonsPerSquareMeterInOnePascal, pascal.As(PressureUnit.KilonewtonPerSquareMeter), KilonewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(KilonewtonsPerSquareMillimeterInOnePascal, pascal.As(PressureUnit.KilonewtonPerSquareMillimeter), KilonewtonsPerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(KilopascalsInOnePascal, pascal.As(PressureUnit.Kilopascal), KilopascalsTolerance);
            AssertEx.EqualTolerance(KilopoundsForcePerSquareFootInOnePascal, pascal.As(PressureUnit.KilopoundForcePerSquareFoot), KilopoundsForcePerSquareFootTolerance);
            AssertEx.EqualTolerance(KilopoundsForcePerSquareInchInOnePascal, pascal.As(PressureUnit.KilopoundForcePerSquareInch), KilopoundsForcePerSquareInchTolerance);
            AssertEx.EqualTolerance(MegabarsInOnePascal, pascal.As(PressureUnit.Megabar), MegabarsTolerance);
            AssertEx.EqualTolerance(MeganewtonsPerSquareMeterInOnePascal, pascal.As(PressureUnit.MeganewtonPerSquareMeter), MeganewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(MegapascalsInOnePascal, pascal.As(PressureUnit.Megapascal), MegapascalsTolerance);
            AssertEx.EqualTolerance(MetersOfElevationInOnePascal, pascal.As(PressureUnit.MeterOfElevation), MetersOfElevationTolerance);
            AssertEx.EqualTolerance(MetersOfHeadInOnePascal, pascal.As(PressureUnit.MeterOfHead), MetersOfHeadTolerance);
            AssertEx.EqualTolerance(MetersOfWaterConventionalInOnePascal, pascal.As(PressureUnit.MeterOfWaterConventional), MetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(MicrobarsInOnePascal, pascal.As(PressureUnit.Microbar), MicrobarsTolerance);
            AssertEx.EqualTolerance(MicropascalsInOnePascal, pascal.As(PressureUnit.Micropascal), MicropascalsTolerance);
            AssertEx.EqualTolerance(MillibarsInOnePascal, pascal.As(PressureUnit.Millibar), MillibarsTolerance);
            AssertEx.EqualTolerance(MillimetersOfMercuryInOnePascal, pascal.As(PressureUnit.MillimeterOfMercury), MillimetersOfMercuryTolerance);
            AssertEx.EqualTolerance(MillimetersOfWaterConventionalInOnePascal, pascal.As(PressureUnit.MillimeterOfWaterConventional), MillimetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(MillipascalsInOnePascal, pascal.As(PressureUnit.Millipascal), MillipascalsTolerance);
            AssertEx.EqualTolerance(NewtonsPerSquareCentimeterInOnePascal, pascal.As(PressureUnit.NewtonPerSquareCentimeter), NewtonsPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(NewtonsPerSquareMeterInOnePascal, pascal.As(PressureUnit.NewtonPerSquareMeter), NewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(NewtonsPerSquareMillimeterInOnePascal, pascal.As(PressureUnit.NewtonPerSquareMillimeter), NewtonsPerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(PascalsInOnePascal, pascal.As(PressureUnit.Pascal), PascalsTolerance);
            AssertEx.EqualTolerance(PoundsForcePerSquareFootInOnePascal, pascal.As(PressureUnit.PoundForcePerSquareFoot), PoundsForcePerSquareFootTolerance);
            AssertEx.EqualTolerance(PoundsForcePerSquareInchInOnePascal, pascal.As(PressureUnit.PoundForcePerSquareInch), PoundsForcePerSquareInchTolerance);
            AssertEx.EqualTolerance(PoundsPerInchSecondSquaredInOnePascal, pascal.As(PressureUnit.PoundPerInchSecondSquared), PoundsPerInchSecondSquaredTolerance);
            AssertEx.EqualTolerance(TechnicalAtmospheresInOnePascal, pascal.As(PressureUnit.TechnicalAtmosphere), TechnicalAtmospheresTolerance);
            AssertEx.EqualTolerance(TonnesForcePerSquareCentimeterInOnePascal, pascal.As(PressureUnit.TonneForcePerSquareCentimeter), TonnesForcePerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(TonnesForcePerSquareMeterInOnePascal, pascal.As(PressureUnit.TonneForcePerSquareMeter), TonnesForcePerSquareMeterTolerance);
            AssertEx.EqualTolerance(TonnesForcePerSquareMillimeterInOnePascal, pascal.As(PressureUnit.TonneForcePerSquareMillimeter), TonnesForcePerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(TorrsInOnePascal, pascal.As(PressureUnit.Torr), TorrsTolerance);
        }

        [Fact]
        public void As_SIUnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var quantity = new Pressure(value: 1, unit: Pressure.BaseUnit);
            Func<object> AsWithSIUnitSystem = () => quantity.As(UnitSystem.SI);

            if (SupportsSIUnitSystem)
            {
                var value = (double) AsWithSIUnitSystem();
                Assert.Equal(1, value);
            }
            else
            {
                Assert.Throws<ArgumentException>(AsWithSIUnitSystem);
            }
        }

        [Fact]
        public void ToUnit()
        {
            var pascal = Pressure.FromPascals(1);

            var atmosphereQuantity = pascal.ToUnit(PressureUnit.Atmosphere);
            AssertEx.EqualTolerance(AtmospheresInOnePascal, (double)atmosphereQuantity.Value, AtmospheresTolerance);
            Assert.Equal(PressureUnit.Atmosphere, atmosphereQuantity.Unit);

            var barQuantity = pascal.ToUnit(PressureUnit.Bar);
            AssertEx.EqualTolerance(BarsInOnePascal, (double)barQuantity.Value, BarsTolerance);
            Assert.Equal(PressureUnit.Bar, barQuantity.Unit);

            var centibarQuantity = pascal.ToUnit(PressureUnit.Centibar);
            AssertEx.EqualTolerance(CentibarsInOnePascal, (double)centibarQuantity.Value, CentibarsTolerance);
            Assert.Equal(PressureUnit.Centibar, centibarQuantity.Unit);

            var centimeterofwaterconventionalQuantity = pascal.ToUnit(PressureUnit.CentimeterOfWaterConventional);
            AssertEx.EqualTolerance(CentimetersOfWaterConventionalInOnePascal, (double)centimeterofwaterconventionalQuantity.Value, CentimetersOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.CentimeterOfWaterConventional, centimeterofwaterconventionalQuantity.Unit);

            var decapascalQuantity = pascal.ToUnit(PressureUnit.Decapascal);
            AssertEx.EqualTolerance(DecapascalsInOnePascal, (double)decapascalQuantity.Value, DecapascalsTolerance);
            Assert.Equal(PressureUnit.Decapascal, decapascalQuantity.Unit);

            var decibarQuantity = pascal.ToUnit(PressureUnit.Decibar);
            AssertEx.EqualTolerance(DecibarsInOnePascal, (double)decibarQuantity.Value, DecibarsTolerance);
            Assert.Equal(PressureUnit.Decibar, decibarQuantity.Unit);

            var dynepersquarecentimeterQuantity = pascal.ToUnit(PressureUnit.DynePerSquareCentimeter);
            AssertEx.EqualTolerance(DynesPerSquareCentimeterInOnePascal, (double)dynepersquarecentimeterQuantity.Value, DynesPerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.DynePerSquareCentimeter, dynepersquarecentimeterQuantity.Unit);

            var footofelevationQuantity = pascal.ToUnit(PressureUnit.FootOfElevation);
            AssertEx.EqualTolerance(FeetOfElevationInOnePascal, (double)footofelevationQuantity.Value, FeetOfElevationTolerance);
            Assert.Equal(PressureUnit.FootOfElevation, footofelevationQuantity.Unit);

            var footofheadQuantity = pascal.ToUnit(PressureUnit.FootOfHead);
            AssertEx.EqualTolerance(FeetOfHeadInOnePascal, (double)footofheadQuantity.Value, FeetOfHeadTolerance);
            Assert.Equal(PressureUnit.FootOfHead, footofheadQuantity.Unit);

            var footofwaterconventionalQuantity = pascal.ToUnit(PressureUnit.FootOfWaterConventional);
            AssertEx.EqualTolerance(FeetOfWaterConventionalInOnePascal, (double)footofwaterconventionalQuantity.Value, FeetOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.FootOfWaterConventional, footofwaterconventionalQuantity.Unit);

            var gigapascalQuantity = pascal.ToUnit(PressureUnit.Gigapascal);
            AssertEx.EqualTolerance(GigapascalsInOnePascal, (double)gigapascalQuantity.Value, GigapascalsTolerance);
            Assert.Equal(PressureUnit.Gigapascal, gigapascalQuantity.Unit);

            var hectopascalQuantity = pascal.ToUnit(PressureUnit.Hectopascal);
            AssertEx.EqualTolerance(HectopascalsInOnePascal, (double)hectopascalQuantity.Value, HectopascalsTolerance);
            Assert.Equal(PressureUnit.Hectopascal, hectopascalQuantity.Unit);

            var inchofmercuryQuantity = pascal.ToUnit(PressureUnit.InchOfMercury);
            AssertEx.EqualTolerance(InchesOfMercuryInOnePascal, (double)inchofmercuryQuantity.Value, InchesOfMercuryTolerance);
            Assert.Equal(PressureUnit.InchOfMercury, inchofmercuryQuantity.Unit);

            var inchofwatercolumnQuantity = pascal.ToUnit(PressureUnit.InchOfWaterColumn);
            AssertEx.EqualTolerance(InchesOfWaterColumnInOnePascal, (double)inchofwatercolumnQuantity.Value, InchesOfWaterColumnTolerance);
            Assert.Equal(PressureUnit.InchOfWaterColumn, inchofwatercolumnQuantity.Unit);

            var inchofwaterconventionalQuantity = pascal.ToUnit(PressureUnit.InchOfWaterConventional);
            AssertEx.EqualTolerance(InchesOfWaterConventionalInOnePascal, (double)inchofwaterconventionalQuantity.Value, InchesOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.InchOfWaterConventional, inchofwaterconventionalQuantity.Unit);

            var kilobarQuantity = pascal.ToUnit(PressureUnit.Kilobar);
            AssertEx.EqualTolerance(KilobarsInOnePascal, (double)kilobarQuantity.Value, KilobarsTolerance);
            Assert.Equal(PressureUnit.Kilobar, kilobarQuantity.Unit);

            var kilogramforcepersquarecentimeterQuantity = pascal.ToUnit(PressureUnit.KilogramForcePerSquareCentimeter);
            AssertEx.EqualTolerance(KilogramsForcePerSquareCentimeterInOnePascal, (double)kilogramforcepersquarecentimeterQuantity.Value, KilogramsForcePerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.KilogramForcePerSquareCentimeter, kilogramforcepersquarecentimeterQuantity.Unit);

            var kilogramforcepersquaremeterQuantity = pascal.ToUnit(PressureUnit.KilogramForcePerSquareMeter);
            AssertEx.EqualTolerance(KilogramsForcePerSquareMeterInOnePascal, (double)kilogramforcepersquaremeterQuantity.Value, KilogramsForcePerSquareMeterTolerance);
            Assert.Equal(PressureUnit.KilogramForcePerSquareMeter, kilogramforcepersquaremeterQuantity.Unit);

            var kilogramforcepersquaremillimeterQuantity = pascal.ToUnit(PressureUnit.KilogramForcePerSquareMillimeter);
            AssertEx.EqualTolerance(KilogramsForcePerSquareMillimeterInOnePascal, (double)kilogramforcepersquaremillimeterQuantity.Value, KilogramsForcePerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.KilogramForcePerSquareMillimeter, kilogramforcepersquaremillimeterQuantity.Unit);

            var kilonewtonpersquarecentimeterQuantity = pascal.ToUnit(PressureUnit.KilonewtonPerSquareCentimeter);
            AssertEx.EqualTolerance(KilonewtonsPerSquareCentimeterInOnePascal, (double)kilonewtonpersquarecentimeterQuantity.Value, KilonewtonsPerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.KilonewtonPerSquareCentimeter, kilonewtonpersquarecentimeterQuantity.Unit);

            var kilonewtonpersquaremeterQuantity = pascal.ToUnit(PressureUnit.KilonewtonPerSquareMeter);
            AssertEx.EqualTolerance(KilonewtonsPerSquareMeterInOnePascal, (double)kilonewtonpersquaremeterQuantity.Value, KilonewtonsPerSquareMeterTolerance);
            Assert.Equal(PressureUnit.KilonewtonPerSquareMeter, kilonewtonpersquaremeterQuantity.Unit);

            var kilonewtonpersquaremillimeterQuantity = pascal.ToUnit(PressureUnit.KilonewtonPerSquareMillimeter);
            AssertEx.EqualTolerance(KilonewtonsPerSquareMillimeterInOnePascal, (double)kilonewtonpersquaremillimeterQuantity.Value, KilonewtonsPerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.KilonewtonPerSquareMillimeter, kilonewtonpersquaremillimeterQuantity.Unit);

            var kilopascalQuantity = pascal.ToUnit(PressureUnit.Kilopascal);
            AssertEx.EqualTolerance(KilopascalsInOnePascal, (double)kilopascalQuantity.Value, KilopascalsTolerance);
            Assert.Equal(PressureUnit.Kilopascal, kilopascalQuantity.Unit);

            var kilopoundforcepersquarefootQuantity = pascal.ToUnit(PressureUnit.KilopoundForcePerSquareFoot);
            AssertEx.EqualTolerance(KilopoundsForcePerSquareFootInOnePascal, (double)kilopoundforcepersquarefootQuantity.Value, KilopoundsForcePerSquareFootTolerance);
            Assert.Equal(PressureUnit.KilopoundForcePerSquareFoot, kilopoundforcepersquarefootQuantity.Unit);

            var kilopoundforcepersquareinchQuantity = pascal.ToUnit(PressureUnit.KilopoundForcePerSquareInch);
            AssertEx.EqualTolerance(KilopoundsForcePerSquareInchInOnePascal, (double)kilopoundforcepersquareinchQuantity.Value, KilopoundsForcePerSquareInchTolerance);
            Assert.Equal(PressureUnit.KilopoundForcePerSquareInch, kilopoundforcepersquareinchQuantity.Unit);

            var megabarQuantity = pascal.ToUnit(PressureUnit.Megabar);
            AssertEx.EqualTolerance(MegabarsInOnePascal, (double)megabarQuantity.Value, MegabarsTolerance);
            Assert.Equal(PressureUnit.Megabar, megabarQuantity.Unit);

            var meganewtonpersquaremeterQuantity = pascal.ToUnit(PressureUnit.MeganewtonPerSquareMeter);
            AssertEx.EqualTolerance(MeganewtonsPerSquareMeterInOnePascal, (double)meganewtonpersquaremeterQuantity.Value, MeganewtonsPerSquareMeterTolerance);
            Assert.Equal(PressureUnit.MeganewtonPerSquareMeter, meganewtonpersquaremeterQuantity.Unit);

            var megapascalQuantity = pascal.ToUnit(PressureUnit.Megapascal);
            AssertEx.EqualTolerance(MegapascalsInOnePascal, (double)megapascalQuantity.Value, MegapascalsTolerance);
            Assert.Equal(PressureUnit.Megapascal, megapascalQuantity.Unit);

            var meterofelevationQuantity = pascal.ToUnit(PressureUnit.MeterOfElevation);
            AssertEx.EqualTolerance(MetersOfElevationInOnePascal, (double)meterofelevationQuantity.Value, MetersOfElevationTolerance);
            Assert.Equal(PressureUnit.MeterOfElevation, meterofelevationQuantity.Unit);

            var meterofheadQuantity = pascal.ToUnit(PressureUnit.MeterOfHead);
            AssertEx.EqualTolerance(MetersOfHeadInOnePascal, (double)meterofheadQuantity.Value, MetersOfHeadTolerance);
            Assert.Equal(PressureUnit.MeterOfHead, meterofheadQuantity.Unit);

            var meterofwaterconventionalQuantity = pascal.ToUnit(PressureUnit.MeterOfWaterConventional);
            AssertEx.EqualTolerance(MetersOfWaterConventionalInOnePascal, (double)meterofwaterconventionalQuantity.Value, MetersOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.MeterOfWaterConventional, meterofwaterconventionalQuantity.Unit);

            var microbarQuantity = pascal.ToUnit(PressureUnit.Microbar);
            AssertEx.EqualTolerance(MicrobarsInOnePascal, (double)microbarQuantity.Value, MicrobarsTolerance);
            Assert.Equal(PressureUnit.Microbar, microbarQuantity.Unit);

            var micropascalQuantity = pascal.ToUnit(PressureUnit.Micropascal);
            AssertEx.EqualTolerance(MicropascalsInOnePascal, (double)micropascalQuantity.Value, MicropascalsTolerance);
            Assert.Equal(PressureUnit.Micropascal, micropascalQuantity.Unit);

            var millibarQuantity = pascal.ToUnit(PressureUnit.Millibar);
            AssertEx.EqualTolerance(MillibarsInOnePascal, (double)millibarQuantity.Value, MillibarsTolerance);
            Assert.Equal(PressureUnit.Millibar, millibarQuantity.Unit);

            var millimeterofmercuryQuantity = pascal.ToUnit(PressureUnit.MillimeterOfMercury);
            AssertEx.EqualTolerance(MillimetersOfMercuryInOnePascal, (double)millimeterofmercuryQuantity.Value, MillimetersOfMercuryTolerance);
            Assert.Equal(PressureUnit.MillimeterOfMercury, millimeterofmercuryQuantity.Unit);

            var millimeterofwaterconventionalQuantity = pascal.ToUnit(PressureUnit.MillimeterOfWaterConventional);
            AssertEx.EqualTolerance(MillimetersOfWaterConventionalInOnePascal, (double)millimeterofwaterconventionalQuantity.Value, MillimetersOfWaterConventionalTolerance);
            Assert.Equal(PressureUnit.MillimeterOfWaterConventional, millimeterofwaterconventionalQuantity.Unit);

            var millipascalQuantity = pascal.ToUnit(PressureUnit.Millipascal);
            AssertEx.EqualTolerance(MillipascalsInOnePascal, (double)millipascalQuantity.Value, MillipascalsTolerance);
            Assert.Equal(PressureUnit.Millipascal, millipascalQuantity.Unit);

            var newtonpersquarecentimeterQuantity = pascal.ToUnit(PressureUnit.NewtonPerSquareCentimeter);
            AssertEx.EqualTolerance(NewtonsPerSquareCentimeterInOnePascal, (double)newtonpersquarecentimeterQuantity.Value, NewtonsPerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.NewtonPerSquareCentimeter, newtonpersquarecentimeterQuantity.Unit);

            var newtonpersquaremeterQuantity = pascal.ToUnit(PressureUnit.NewtonPerSquareMeter);
            AssertEx.EqualTolerance(NewtonsPerSquareMeterInOnePascal, (double)newtonpersquaremeterQuantity.Value, NewtonsPerSquareMeterTolerance);
            Assert.Equal(PressureUnit.NewtonPerSquareMeter, newtonpersquaremeterQuantity.Unit);

            var newtonpersquaremillimeterQuantity = pascal.ToUnit(PressureUnit.NewtonPerSquareMillimeter);
            AssertEx.EqualTolerance(NewtonsPerSquareMillimeterInOnePascal, (double)newtonpersquaremillimeterQuantity.Value, NewtonsPerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.NewtonPerSquareMillimeter, newtonpersquaremillimeterQuantity.Unit);

            var pascalQuantity = pascal.ToUnit(PressureUnit.Pascal);
            AssertEx.EqualTolerance(PascalsInOnePascal, (double)pascalQuantity.Value, PascalsTolerance);
            Assert.Equal(PressureUnit.Pascal, pascalQuantity.Unit);

            var poundforcepersquarefootQuantity = pascal.ToUnit(PressureUnit.PoundForcePerSquareFoot);
            AssertEx.EqualTolerance(PoundsForcePerSquareFootInOnePascal, (double)poundforcepersquarefootQuantity.Value, PoundsForcePerSquareFootTolerance);
            Assert.Equal(PressureUnit.PoundForcePerSquareFoot, poundforcepersquarefootQuantity.Unit);

            var poundforcepersquareinchQuantity = pascal.ToUnit(PressureUnit.PoundForcePerSquareInch);
            AssertEx.EqualTolerance(PoundsForcePerSquareInchInOnePascal, (double)poundforcepersquareinchQuantity.Value, PoundsForcePerSquareInchTolerance);
            Assert.Equal(PressureUnit.PoundForcePerSquareInch, poundforcepersquareinchQuantity.Unit);

            var poundperinchsecondsquaredQuantity = pascal.ToUnit(PressureUnit.PoundPerInchSecondSquared);
            AssertEx.EqualTolerance(PoundsPerInchSecondSquaredInOnePascal, (double)poundperinchsecondsquaredQuantity.Value, PoundsPerInchSecondSquaredTolerance);
            Assert.Equal(PressureUnit.PoundPerInchSecondSquared, poundperinchsecondsquaredQuantity.Unit);

            var technicalatmosphereQuantity = pascal.ToUnit(PressureUnit.TechnicalAtmosphere);
            AssertEx.EqualTolerance(TechnicalAtmospheresInOnePascal, (double)technicalatmosphereQuantity.Value, TechnicalAtmospheresTolerance);
            Assert.Equal(PressureUnit.TechnicalAtmosphere, technicalatmosphereQuantity.Unit);

            var tonneforcepersquarecentimeterQuantity = pascal.ToUnit(PressureUnit.TonneForcePerSquareCentimeter);
            AssertEx.EqualTolerance(TonnesForcePerSquareCentimeterInOnePascal, (double)tonneforcepersquarecentimeterQuantity.Value, TonnesForcePerSquareCentimeterTolerance);
            Assert.Equal(PressureUnit.TonneForcePerSquareCentimeter, tonneforcepersquarecentimeterQuantity.Unit);

            var tonneforcepersquaremeterQuantity = pascal.ToUnit(PressureUnit.TonneForcePerSquareMeter);
            AssertEx.EqualTolerance(TonnesForcePerSquareMeterInOnePascal, (double)tonneforcepersquaremeterQuantity.Value, TonnesForcePerSquareMeterTolerance);
            Assert.Equal(PressureUnit.TonneForcePerSquareMeter, tonneforcepersquaremeterQuantity.Unit);

            var tonneforcepersquaremillimeterQuantity = pascal.ToUnit(PressureUnit.TonneForcePerSquareMillimeter);
            AssertEx.EqualTolerance(TonnesForcePerSquareMillimeterInOnePascal, (double)tonneforcepersquaremillimeterQuantity.Value, TonnesForcePerSquareMillimeterTolerance);
            Assert.Equal(PressureUnit.TonneForcePerSquareMillimeter, tonneforcepersquaremillimeterQuantity.Unit);

            var torrQuantity = pascal.ToUnit(PressureUnit.Torr);
            AssertEx.EqualTolerance(TorrsInOnePascal, (double)torrQuantity.Value, TorrsTolerance);
            Assert.Equal(PressureUnit.Torr, torrQuantity.Unit);
        }

        [Fact]
        public void ToBaseUnit_ReturnsQuantityWithBaseUnit()
        {
            var quantityInBaseUnit = Pressure.FromPascals(1).ToBaseUnit();
            Assert.Equal(Pressure.BaseUnit, quantityInBaseUnit.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            Pressure pascal = Pressure.FromPascals(1);
            AssertEx.EqualTolerance(1, Pressure.FromAtmospheres(pascal.Atmospheres).Pascals, AtmospheresTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromBars(pascal.Bars).Pascals, BarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromCentibars(pascal.Centibars).Pascals, CentibarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromCentimetersOfWaterConventional(pascal.CentimetersOfWaterConventional).Pascals, CentimetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromDecapascals(pascal.Decapascals).Pascals, DecapascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromDecibars(pascal.Decibars).Pascals, DecibarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromDynesPerSquareCentimeter(pascal.DynesPerSquareCentimeter).Pascals, DynesPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromFeetOfElevation(pascal.FeetOfElevation).Pascals, FeetOfElevationTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromFeetOfHead(pascal.FeetOfHead).Pascals, FeetOfHeadTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromFeetOfWaterConventional(pascal.FeetOfWaterConventional).Pascals, FeetOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromGigapascals(pascal.Gigapascals).Pascals, GigapascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromHectopascals(pascal.Hectopascals).Pascals, HectopascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromInchesOfMercury(pascal.InchesOfMercury).Pascals, InchesOfMercuryTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromInchesOfWaterColumn(pascal.InchesOfWaterColumn).Pascals, InchesOfWaterColumnTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromInchesOfWaterConventional(pascal.InchesOfWaterConventional).Pascals, InchesOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilobars(pascal.Kilobars).Pascals, KilobarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilogramsForcePerSquareCentimeter(pascal.KilogramsForcePerSquareCentimeter).Pascals, KilogramsForcePerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilogramsForcePerSquareMeter(pascal.KilogramsForcePerSquareMeter).Pascals, KilogramsForcePerSquareMeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilogramsForcePerSquareMillimeter(pascal.KilogramsForcePerSquareMillimeter).Pascals, KilogramsForcePerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilonewtonsPerSquareCentimeter(pascal.KilonewtonsPerSquareCentimeter).Pascals, KilonewtonsPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilonewtonsPerSquareMeter(pascal.KilonewtonsPerSquareMeter).Pascals, KilonewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilonewtonsPerSquareMillimeter(pascal.KilonewtonsPerSquareMillimeter).Pascals, KilonewtonsPerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilopascals(pascal.Kilopascals).Pascals, KilopascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilopoundsForcePerSquareFoot(pascal.KilopoundsForcePerSquareFoot).Pascals, KilopoundsForcePerSquareFootTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromKilopoundsForcePerSquareInch(pascal.KilopoundsForcePerSquareInch).Pascals, KilopoundsForcePerSquareInchTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMegabars(pascal.Megabars).Pascals, MegabarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMeganewtonsPerSquareMeter(pascal.MeganewtonsPerSquareMeter).Pascals, MeganewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMegapascals(pascal.Megapascals).Pascals, MegapascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMetersOfElevation(pascal.MetersOfElevation).Pascals, MetersOfElevationTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMetersOfHead(pascal.MetersOfHead).Pascals, MetersOfHeadTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMetersOfWaterConventional(pascal.MetersOfWaterConventional).Pascals, MetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMicrobars(pascal.Microbars).Pascals, MicrobarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMicropascals(pascal.Micropascals).Pascals, MicropascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMillibars(pascal.Millibars).Pascals, MillibarsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMillimetersOfMercury(pascal.MillimetersOfMercury).Pascals, MillimetersOfMercuryTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMillimetersOfWaterConventional(pascal.MillimetersOfWaterConventional).Pascals, MillimetersOfWaterConventionalTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromMillipascals(pascal.Millipascals).Pascals, MillipascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromNewtonsPerSquareCentimeter(pascal.NewtonsPerSquareCentimeter).Pascals, NewtonsPerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromNewtonsPerSquareMeter(pascal.NewtonsPerSquareMeter).Pascals, NewtonsPerSquareMeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromNewtonsPerSquareMillimeter(pascal.NewtonsPerSquareMillimeter).Pascals, NewtonsPerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromPascals(pascal.Pascals).Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromPoundsForcePerSquareFoot(pascal.PoundsForcePerSquareFoot).Pascals, PoundsForcePerSquareFootTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromPoundsForcePerSquareInch(pascal.PoundsForcePerSquareInch).Pascals, PoundsForcePerSquareInchTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromPoundsPerInchSecondSquared(pascal.PoundsPerInchSecondSquared).Pascals, PoundsPerInchSecondSquaredTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromTechnicalAtmospheres(pascal.TechnicalAtmospheres).Pascals, TechnicalAtmospheresTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromTonnesForcePerSquareCentimeter(pascal.TonnesForcePerSquareCentimeter).Pascals, TonnesForcePerSquareCentimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromTonnesForcePerSquareMeter(pascal.TonnesForcePerSquareMeter).Pascals, TonnesForcePerSquareMeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromTonnesForcePerSquareMillimeter(pascal.TonnesForcePerSquareMillimeter).Pascals, TonnesForcePerSquareMillimeterTolerance);
            AssertEx.EqualTolerance(1, Pressure.FromTorrs(pascal.Torrs).Pascals, TorrsTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            Pressure v = Pressure.FromPascals(1);
            AssertEx.EqualTolerance(-1, -v.Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(2, (Pressure.FromPascals(3)-v).Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(2, (v + v).Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(10, (v*10).Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(10, (10*v).Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(2, (Pressure.FromPascals(10)/5).Pascals, PascalsTolerance);
            AssertEx.EqualTolerance(2, Pressure.FromPascals(10)/Pressure.FromPascals(5), PascalsTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            Pressure onePascal = Pressure.FromPascals(1);
            Pressure twoPascals = Pressure.FromPascals(2);

            Assert.True(onePascal < twoPascals);
            Assert.True(onePascal <= twoPascals);
            Assert.True(twoPascals > onePascal);
            Assert.True(twoPascals >= onePascal);

            Assert.False(onePascal > twoPascals);
            Assert.False(onePascal >= twoPascals);
            Assert.False(twoPascals < onePascal);
            Assert.False(twoPascals <= onePascal);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            Pressure pascal = Pressure.FromPascals(1);
            Assert.Equal(0, pascal.CompareTo(pascal));
            Assert.True(pascal.CompareTo(Pressure.Zero) > 0);
            Assert.True(Pressure.Zero.CompareTo(pascal) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            Pressure pascal = Pressure.FromPascals(1);
            Assert.Throws<ArgumentException>(() => pascal.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            Pressure pascal = Pressure.FromPascals(1);
            Assert.Throws<ArgumentNullException>(() => pascal.CompareTo(null));
        }

        [Fact]
        public void EqualityOperators()
        {
            var a = Pressure.FromPascals(1);
            var b = Pressure.FromPascals(2);

#pragma warning disable CS8073
// ReSharper disable EqualExpressionComparison

            Assert.True(a == a);
            Assert.False(a != a);

            Assert.True(a != b);
            Assert.False(a == b);

            Assert.False(a == null);
            Assert.False(null == a);

// ReSharper restore EqualExpressionComparison
#pragma warning restore CS8073
        }

        [Fact]
        public void Equals_SameType_IsImplemented()
        {
            var a = Pressure.FromPascals(1);
            var b = Pressure.FromPascals(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
        }

        [Fact]
        public void Equals_QuantityAsObject_IsImplemented()
        {
            object a = Pressure.FromPascals(1);
            object b = Pressure.FromPascals(2);

            Assert.True(a.Equals(a));
            Assert.False(a.Equals(b));
            Assert.False(a.Equals((object)null));
        }

        [Fact]
        public void Equals_RelativeTolerance_IsImplemented()
        {
            var v = Pressure.FromPascals(1);
            Assert.True(v.Equals(Pressure.FromPascals(1), PascalsTolerance, ComparisonType.Relative));
            Assert.False(v.Equals(Pressure.Zero, PascalsTolerance, ComparisonType.Relative));
        }

        [Fact]
        public void Equals_NegativeRelativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = Pressure.FromPascals(1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(Pressure.FromPascals(1), -1, ComparisonType.Relative));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            Pressure pascal = Pressure.FromPascals(1);
            Assert.False(pascal.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            Pressure pascal = Pressure.FromPascals(1);
            Assert.False(pascal.Equals(null));
        }

        [Fact]
        public void UnitsDoesNotContainUndefined()
        {
            Assert.DoesNotContain(PressureUnit.Undefined, Pressure.Units);
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(PressureUnit)).Cast<PressureUnit>();
            foreach(var unit in units)
            {
                if(unit == PressureUnit.Undefined)
                    continue;

                var defaultAbbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(Pressure.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 atm", new Pressure(1, PressureUnit.Atmosphere).ToString());
                Assert.Equal("1 bar", new Pressure(1, PressureUnit.Bar).ToString());
                Assert.Equal("1 cbar", new Pressure(1, PressureUnit.Centibar).ToString());
                Assert.Equal("1 cmH2O", new Pressure(1, PressureUnit.CentimeterOfWaterConventional).ToString());
                Assert.Equal("1 daPa", new Pressure(1, PressureUnit.Decapascal).ToString());
                Assert.Equal("1 dbar", new Pressure(1, PressureUnit.Decibar).ToString());
                Assert.Equal("1 dyn/cm²", new Pressure(1, PressureUnit.DynePerSquareCentimeter).ToString());
                Assert.Equal("1 ft of elevation", new Pressure(1, PressureUnit.FootOfElevation).ToString());
                Assert.Equal("1 ft of head", new Pressure(1, PressureUnit.FootOfHead).ToString());
                Assert.Equal("1 ftH2O", new Pressure(1, PressureUnit.FootOfWaterConventional).ToString());
                Assert.Equal("1 GPa", new Pressure(1, PressureUnit.Gigapascal).ToString());
                Assert.Equal("1 hPa", new Pressure(1, PressureUnit.Hectopascal).ToString());
                Assert.Equal("1 inHg", new Pressure(1, PressureUnit.InchOfMercury).ToString());
                Assert.Equal("1 wc", new Pressure(1, PressureUnit.InchOfWaterColumn).ToString());
                Assert.Equal("1 inH2O", new Pressure(1, PressureUnit.InchOfWaterConventional).ToString());
                Assert.Equal("1 kbar", new Pressure(1, PressureUnit.Kilobar).ToString());
                Assert.Equal("1 kgf/cm²", new Pressure(1, PressureUnit.KilogramForcePerSquareCentimeter).ToString());
                Assert.Equal("1 kgf/m²", new Pressure(1, PressureUnit.KilogramForcePerSquareMeter).ToString());
                Assert.Equal("1 kgf/mm²", new Pressure(1, PressureUnit.KilogramForcePerSquareMillimeter).ToString());
                Assert.Equal("1 kN/cm²", new Pressure(1, PressureUnit.KilonewtonPerSquareCentimeter).ToString());
                Assert.Equal("1 kN/m²", new Pressure(1, PressureUnit.KilonewtonPerSquareMeter).ToString());
                Assert.Equal("1 kN/mm²", new Pressure(1, PressureUnit.KilonewtonPerSquareMillimeter).ToString());
                Assert.Equal("1 kPa", new Pressure(1, PressureUnit.Kilopascal).ToString());
                Assert.Equal("1 kipf/ft²", new Pressure(1, PressureUnit.KilopoundForcePerSquareFoot).ToString());
                Assert.Equal("1 ksi", new Pressure(1, PressureUnit.KilopoundForcePerSquareInch).ToString());
                Assert.Equal("1 Mbar", new Pressure(1, PressureUnit.Megabar).ToString());
                Assert.Equal("1 MN/m²", new Pressure(1, PressureUnit.MeganewtonPerSquareMeter).ToString());
                Assert.Equal("1 MPa", new Pressure(1, PressureUnit.Megapascal).ToString());
                Assert.Equal("1 m of elevation", new Pressure(1, PressureUnit.MeterOfElevation).ToString());
                Assert.Equal("1 m of head", new Pressure(1, PressureUnit.MeterOfHead).ToString());
                Assert.Equal("1 mH2O", new Pressure(1, PressureUnit.MeterOfWaterConventional).ToString());
                Assert.Equal("1 µbar", new Pressure(1, PressureUnit.Microbar).ToString());
                Assert.Equal("1 µPa", new Pressure(1, PressureUnit.Micropascal).ToString());
                Assert.Equal("1 mbar", new Pressure(1, PressureUnit.Millibar).ToString());
                Assert.Equal("1 mmHg", new Pressure(1, PressureUnit.MillimeterOfMercury).ToString());
                Assert.Equal("1 mmH2O", new Pressure(1, PressureUnit.MillimeterOfWaterConventional).ToString());
                Assert.Equal("1 mPa", new Pressure(1, PressureUnit.Millipascal).ToString());
                Assert.Equal("1 N/cm²", new Pressure(1, PressureUnit.NewtonPerSquareCentimeter).ToString());
                Assert.Equal("1 N/m²", new Pressure(1, PressureUnit.NewtonPerSquareMeter).ToString());
                Assert.Equal("1 N/mm²", new Pressure(1, PressureUnit.NewtonPerSquareMillimeter).ToString());
                Assert.Equal("1 Pa", new Pressure(1, PressureUnit.Pascal).ToString());
                Assert.Equal("1 lb/ft²", new Pressure(1, PressureUnit.PoundForcePerSquareFoot).ToString());
                Assert.Equal("1 psi", new Pressure(1, PressureUnit.PoundForcePerSquareInch).ToString());
                Assert.Equal("1 lbm/(in·s²)", new Pressure(1, PressureUnit.PoundPerInchSecondSquared).ToString());
                Assert.Equal("1 at", new Pressure(1, PressureUnit.TechnicalAtmosphere).ToString());
                Assert.Equal("1 tf/cm²", new Pressure(1, PressureUnit.TonneForcePerSquareCentimeter).ToString());
                Assert.Equal("1 tf/m²", new Pressure(1, PressureUnit.TonneForcePerSquareMeter).ToString());
                Assert.Equal("1 tf/mm²", new Pressure(1, PressureUnit.TonneForcePerSquareMillimeter).ToString());
                Assert.Equal("1 torr", new Pressure(1, PressureUnit.Torr).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentUICulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 atm", new Pressure(1, PressureUnit.Atmosphere).ToString(swedishCulture));
            Assert.Equal("1 bar", new Pressure(1, PressureUnit.Bar).ToString(swedishCulture));
            Assert.Equal("1 cbar", new Pressure(1, PressureUnit.Centibar).ToString(swedishCulture));
            Assert.Equal("1 cmH2O", new Pressure(1, PressureUnit.CentimeterOfWaterConventional).ToString(swedishCulture));
            Assert.Equal("1 daPa", new Pressure(1, PressureUnit.Decapascal).ToString(swedishCulture));
            Assert.Equal("1 dbar", new Pressure(1, PressureUnit.Decibar).ToString(swedishCulture));
            Assert.Equal("1 dyn/cm²", new Pressure(1, PressureUnit.DynePerSquareCentimeter).ToString(swedishCulture));
            Assert.Equal("1 ft of elevation", new Pressure(1, PressureUnit.FootOfElevation).ToString(swedishCulture));
            Assert.Equal("1 ft of head", new Pressure(1, PressureUnit.FootOfHead).ToString(swedishCulture));
            Assert.Equal("1 ftH2O", new Pressure(1, PressureUnit.FootOfWaterConventional).ToString(swedishCulture));
            Assert.Equal("1 GPa", new Pressure(1, PressureUnit.Gigapascal).ToString(swedishCulture));
            Assert.Equal("1 hPa", new Pressure(1, PressureUnit.Hectopascal).ToString(swedishCulture));
            Assert.Equal("1 inHg", new Pressure(1, PressureUnit.InchOfMercury).ToString(swedishCulture));
            Assert.Equal("1 wc", new Pressure(1, PressureUnit.InchOfWaterColumn).ToString(swedishCulture));
            Assert.Equal("1 inH2O", new Pressure(1, PressureUnit.InchOfWaterConventional).ToString(swedishCulture));
            Assert.Equal("1 kbar", new Pressure(1, PressureUnit.Kilobar).ToString(swedishCulture));
            Assert.Equal("1 kgf/cm²", new Pressure(1, PressureUnit.KilogramForcePerSquareCentimeter).ToString(swedishCulture));
            Assert.Equal("1 kgf/m²", new Pressure(1, PressureUnit.KilogramForcePerSquareMeter).ToString(swedishCulture));
            Assert.Equal("1 kgf/mm²", new Pressure(1, PressureUnit.KilogramForcePerSquareMillimeter).ToString(swedishCulture));
            Assert.Equal("1 kN/cm²", new Pressure(1, PressureUnit.KilonewtonPerSquareCentimeter).ToString(swedishCulture));
            Assert.Equal("1 kN/m²", new Pressure(1, PressureUnit.KilonewtonPerSquareMeter).ToString(swedishCulture));
            Assert.Equal("1 kN/mm²", new Pressure(1, PressureUnit.KilonewtonPerSquareMillimeter).ToString(swedishCulture));
            Assert.Equal("1 kPa", new Pressure(1, PressureUnit.Kilopascal).ToString(swedishCulture));
            Assert.Equal("1 kipf/ft²", new Pressure(1, PressureUnit.KilopoundForcePerSquareFoot).ToString(swedishCulture));
            Assert.Equal("1 ksi", new Pressure(1, PressureUnit.KilopoundForcePerSquareInch).ToString(swedishCulture));
            Assert.Equal("1 Mbar", new Pressure(1, PressureUnit.Megabar).ToString(swedishCulture));
            Assert.Equal("1 MN/m²", new Pressure(1, PressureUnit.MeganewtonPerSquareMeter).ToString(swedishCulture));
            Assert.Equal("1 MPa", new Pressure(1, PressureUnit.Megapascal).ToString(swedishCulture));
            Assert.Equal("1 m of elevation", new Pressure(1, PressureUnit.MeterOfElevation).ToString(swedishCulture));
            Assert.Equal("1 m of head", new Pressure(1, PressureUnit.MeterOfHead).ToString(swedishCulture));
            Assert.Equal("1 mH2O", new Pressure(1, PressureUnit.MeterOfWaterConventional).ToString(swedishCulture));
            Assert.Equal("1 µbar", new Pressure(1, PressureUnit.Microbar).ToString(swedishCulture));
            Assert.Equal("1 µPa", new Pressure(1, PressureUnit.Micropascal).ToString(swedishCulture));
            Assert.Equal("1 mbar", new Pressure(1, PressureUnit.Millibar).ToString(swedishCulture));
            Assert.Equal("1 mmHg", new Pressure(1, PressureUnit.MillimeterOfMercury).ToString(swedishCulture));
            Assert.Equal("1 mmH2O", new Pressure(1, PressureUnit.MillimeterOfWaterConventional).ToString(swedishCulture));
            Assert.Equal("1 mPa", new Pressure(1, PressureUnit.Millipascal).ToString(swedishCulture));
            Assert.Equal("1 N/cm²", new Pressure(1, PressureUnit.NewtonPerSquareCentimeter).ToString(swedishCulture));
            Assert.Equal("1 N/m²", new Pressure(1, PressureUnit.NewtonPerSquareMeter).ToString(swedishCulture));
            Assert.Equal("1 N/mm²", new Pressure(1, PressureUnit.NewtonPerSquareMillimeter).ToString(swedishCulture));
            Assert.Equal("1 Pa", new Pressure(1, PressureUnit.Pascal).ToString(swedishCulture));
            Assert.Equal("1 lb/ft²", new Pressure(1, PressureUnit.PoundForcePerSquareFoot).ToString(swedishCulture));
            Assert.Equal("1 psi", new Pressure(1, PressureUnit.PoundForcePerSquareInch).ToString(swedishCulture));
            Assert.Equal("1 lbm/(in·s²)", new Pressure(1, PressureUnit.PoundPerInchSecondSquared).ToString(swedishCulture));
            Assert.Equal("1 at", new Pressure(1, PressureUnit.TechnicalAtmosphere).ToString(swedishCulture));
            Assert.Equal("1 tf/cm²", new Pressure(1, PressureUnit.TonneForcePerSquareCentimeter).ToString(swedishCulture));
            Assert.Equal("1 tf/m²", new Pressure(1, PressureUnit.TonneForcePerSquareMeter).ToString(swedishCulture));
            Assert.Equal("1 tf/mm²", new Pressure(1, PressureUnit.TonneForcePerSquareMillimeter).ToString(swedishCulture));
            Assert.Equal("1 torr", new Pressure(1, PressureUnit.Torr).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentUICulture;
            try
            {
                CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s1"));
                Assert.Equal("0.12 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s2"));
                Assert.Equal("0.123 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s3"));
                Assert.Equal("0.1235 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentUICulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s1", culture));
            Assert.Equal("0.12 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s2", culture));
            Assert.Equal("0.123 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s3", culture));
            Assert.Equal("0.1235 Pa", new Pressure(0.123456, PressureUnit.Pascal).ToString("s4", culture));
        }


        [Fact]
        public void ToString_NullFormat_ThrowsArgumentNullException()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, null, null));
        }

        [Fact]
        public void ToString_NullArgs_ThrowsArgumentNullException()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Throws<ArgumentNullException>(() => quantity.ToString(null, "g", null));
        }

        [Fact]
        public void ToString_NullProvider_EqualsCurrentUICulture()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(quantity.ToString(CultureInfo.CurrentUICulture, "g"), quantity.ToString(null, "g"));
        }


        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(Pressure)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(PressureUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityType_EqualsQuantityType()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(QuantityType.Pressure, Convert.ChangeType(quantity, typeof(QuantityType)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityInfo_EqualsQuantityInfo()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(Pressure.Info, Convert.ChangeType(quantity, typeof(QuantityInfo)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(Pressure.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = Pressure.FromPascals(1.0);
            Assert.Equal(new {Pressure.Info.Name, quantity.Value, quantity.Unit}.GetHashCode(), quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = Pressure.FromPascals(value);
            Assert.Equal(Pressure.FromPascals(-value), -quantity);
        }
    }
}
